---

- name: "install helm chart for sales kafka streams application"
  kubernetes.core.helm:
    name: "{{ sales_streams_app_helm_chart }}"
    chart_ref: "{{ helm_repo_name }}/{{ sales_streams_app_helm_chart }}"
    release_namespace: "{{ application_namespace }}"
    values:
      kafka:
        bootstrapServer:  "{{ rhosak_bootstrap_server }}"
        userId: "{{ rhosak_service_account_client_id }}"
        password: "{{ rhosak_service_account_client_secret }}"
        streams:
          replicationFactor: 1