---

- name: "deploy elasticsearch operator in openshift-operators namespace"
  import_role:
    name: openshift-operator
  vars:
    operator_name: elasticsearch-operator
    packagemanifest: "{{ elasticsearch_operator_packagemanifest }}"
    subscription_channel: "{{ elasticsearch_operator_subscription_channel }}"
    subscription_namespace: "openshift-operators"
    subscription_name: "{{ elasticsearch_operator_subscription_name }}"
    automatic_installplan_approval: "{{ elasticsearch_operator_subscription_automatic_installplan_approval }}"
    subscription_starting_csv: "{{ elasticsearch_operator_subscription_starting_csv }}"
    csv_prefix: "{{ elasticsearch_operator_csv_prefix }}"
  