---
- name: "get cashback-db secret"
  k8s_info:
    api_version: v1
    kind: secret
    namespace: "{{ application_namespace }}"
    name: "{{ cashback_db_secret }}"
  register: r_cashback_db_credentials

- name: "get cashback-db credentials"
  set_fact:
    cashback_db_username: "{{ r_cashback_db_credentials.resources[0].data['database-user'] | b64decode  }}"
    cashback_db_password: "{{ r_cashback_db_credentials.resources[0].data['database-password'] | b64decode  }}"
    cashback_db_database: "{{ r_cashback_db_credentials.resources[0].data['database-name'] | b64decode  }}"

- name: "install helm chart for cashback service ui"
  kubernetes.core.helm:
    name: "{{ cashback_service_ui_helm_chart }}"
    chart_ref: "{{ helm_repo_name }}/{{ cashback_service_ui_helm_chart }}"
    release_namespace: "{{ application_namespace }}"
    values:
      postgresql:
        host: "{{ cashback_db_service }}.{{ application_namespace }}.svc"
        username: "{{ cashback_db_username }}"
        password: "{{  cashback_db_password }}"
        database: "{{ cashback_db_database }}"
      default_page_size: 15
