---

- name: "wait until Kafka Connect is deployed and ready"
  import_role:
    name: kafka-connect
    tasks_from: kafka-connect-deployed

- name: "get retail-db secret"
  k8s_info:
    api_version: v1
    kind: secret
    namespace: "{{ application_namespace }}"
    name: "{{ retail_db_secret }}"
  register: r_retail_db_credentials

- name: "get retail-db credentials"
  set_fact:
    retail_db_admin_password: "{{ r_retail_db_credentials.resources[0].data['database-admin-password'] | b64decode }}"
    retail_db_database: "{{ r_retail_db_credentials.resources[0].data['database-name'] | b64decode }}"

- name: "install helm chart for Debezium connector"
  kubernetes.core.helm:
    name: "{{ debezium_helm_chart }}"
    chart_ref: "{{ helm_repo_name }}/{{ debezium_helm_chart }}"
    release_namespace: "{{ application_namespace }}"
    values:
      kafkaConnect: "{{ kafka_connect_name }}"
      database:
        hostname: "{{ retail_db_service }}"
        user: "{{ retail_db_admin_user }}"
        password: "{{ retail_db_admin_password }}"
        dbname: "{{ retail_db_database }}"
      topic:
        replicationFactor: "{{ rhosak_replication_factor }}"
