---

- name: "get elasticsearch credentials secret"
  k8s_info:
    api_version: v1
    kind: secret
    namespace: "{{ application_namespace }}"
    name: "{{ elasticsearch_cluster_name }}-es-{{ elasticsearch_user_name }}-user"
  register: r_elasticsearch_credentials

- set_fact:
    elasticsearch_user_password: "{{ r_elasticsearch_credentials.resources[0].data[elasticsearch_user_name] | b64decode }}"

- name: "install helm chart for search service"
  kubernetes.core.helm:
    name: "{{ search_service_helm_chart }}"
    chart_ref: "{{ helm_repo_name }}/{{ search_service_helm_chart }}"
    release_namespace: "{{ application_namespace }}"
    values:
      elasticsearch:
        hosts: "{{ elasticsearch_cluster_name }}-es-http.{{ application_namespace }}.svc:9200"
        username: "{{ elasticsearch_user_name }}"
        password: "{{ elasticsearch_user_password }}"
        protocol: http
        index: products
