---

- name: "install helm chart for retail database"
  kubernetes.core.helm:
    name: "{{ retail_helm_chart }}"
    chart_ref: "{{ helm_repo_name }}/{{ retail_helm_chart }}"
    release_namespace: "{{ application_namespace }}"
