---

- name: "ununstall kafdrop"
  k8s:
    state: absent
    api_version: "{{ item.api_version }}"
    kind: "{{ item.kind }}"
    namespace: "{{ application_namespace }}"
    name: "{{ item.name }}"
  loop:
    - api_version: route.openshift.io/v1
      kind: route
      name: "{{ kafdrop_application }}"
    - api_version: v1
      kind: service
      name: "{{ kafdrop_application }}"
    - api_version: apps/v1
      kind: deployment
      name: "{{ kafdrop_application }}"
    - api_version: v1
      kind: secret
      name: "{{ kafdrop_secret }}"
    - api_version: v1
      kind: serviceaccount
      name: "{{ kafdrop_service_account }}"
