---

- name: "wait until Kafka Connect is ready"
  k8s_info:
    api_version: v1
    kind: Deployment
    namespace: "{{ application_namespace }}"
    name: "{{ kafka_connect_deployment }}"
  register: r_kafka_connect_deployment
  retries: 20
  delay: 10
  until:
    - r_kafka_connect_deployment.resources is defined
    - r_kafka_connect_deployment.resources | length | int > 0
    - r_kafka_connect_deployment.resources[0].status.availableReplicas is defined
    - r_kafka_connect_deployment.resources[0].status.availableReplicas | int == r_kafka_connect_deployment.resources[0].spec.replicas | int  