---

- name: "deploy amq streams operator in openshift-operators namespace"
  import_role:
    name: openshift-operator
  vars:
    operator_name: amq-streams-operator
    packagemanifest: "{{ amq_streams_operator_packagemanifest }}"
    subscription_channel: "{{ amq_streams_operator_subscription_channel }}"
    subscription_namespace: "openshift-operators"
    subscription_name: "{{ amq_streams_operator_subscription_name }}"
    automatic_installplan_approval: "{{ amq_streams_operator_subscription_automatic_installplan_approval }}"
    subscription_starting_csv: "{{ amq_streams_operator_subscription_starting_csv }}"
    csv_prefix: "{{ amq_streams_operator_csv_prefix }}"