---

- name: Install Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: amq-streams
    install_operator_namespace: openshift-operators
    install_operator_channel: "{{ amq_streams_channel }}"
    install_operator_csv_nameprefix: amqstreams
    install_operator_catalog: redhat-operators
    install_operator_automatic_install_plan_approval: "{{ amq_streams_automatic_install_plan_approval | default(true) }}"
    install_operator_starting_csv: "{{ amq_streams_starting_csv }}"
    install_operator_catalogsource_setup: "{{ amq_streams_use_catalog_snapshot | default(false) }}"
    install_operator_catalogsource_name: "{{ amq_streams_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace: openshift-operators
    install_operator_catalogsource_image: "{{ amq_streams_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag: "{{ amq_streams_catalog_snapshot_image_tag | default('') }}"
