---

- name: "wait until elasticsearch instance is up and running"
  import_role:
    name: elasticsearch
    tasks_from: elasticsearch-deployed.yml

- name: "get elasticsearch credentials secret"
  k8s_info:
    api_version: v1
    kind: secret
    namespace: "{{ application_namespace }}"
    name: "{{ elasticsearch_cluster_name }}-es-{{ elasticsearch_user_name }}-user"
  register: r_elasticsearch_credentials

- set_fact:
    elasticsearch_user_password: "{{ r_elasticsearch_credentials.resources[0].data[elasticsearch_user_name] | b64decode }}"

- name: "install helm chart for elasticsearch connector"
  kubernetes.core.helm:
    name: "{{ elasticsearch_connector_helm_chart }}"
    chart_ref: "{{ helm_repo_name }}/{{ elasticsearch_connector_helm_chart }}"
    release_namespace: "{{ application_namespace }}"
    values:
      kafka:
        bootstrapServer:  "{{ rhosak_bootstrap_server }}"
        userId: "{{ rhosak_service_account_client_id }}"
        password: "{{ rhosak_service_account_client_secret }}"
      elasticsearch:
        hosts: "{{ elasticsearch_cluster_name }}-es-http.{{ application_namespace }}.svc:9200"
        username: "{{ elasticsearch_user_name }}"
        password: "{{ elasticsearch_user_password }}"