---

- name: "wait until ElasticSearch instance is ready"
  k8s_info:
    api_version: v1
    kind: StatefulSet
    namespace: "{{ application_namespace }}"
    name: "{{ elasticsearch_statefulset }}"
  register: r_elasticsearch_deployment
  retries: 30
  delay: 10
  until:
    - r_elasticsearch_deployment.resources is defined
    - r_elasticsearch_deployment.resources | length | int > 0
    - r_elasticsearch_deployment.resources[0].status.availableReplicas is defined
    - r_elasticsearch_deployment.resources[0].status.availableReplicas | int == r_elasticsearch_deployment.resources[0].spec.replicas | int  
