---

- name: Install Retail Application
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true

  tasks:
    - name: "Install solution pattern"
      ansible.builtin.include_role:
        name: install
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - name: "Unnstall solution pattern"
      ansible.builtin.include_role:
        name: install
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"
