---

- name: "install AMQ Streams operator"
  import_role:
    name: amq-streams-operator

- name: "install ElasticSearch operator"
  import_role:
    name: elasticsearch-operator

- name: "install retail-db database"
  import_role:
    name: retail-db

- name: "install Kafka Connect"
  import_role:
    name: kafka-connect

- name: "install debezium connector"
  import_role:
    name: debezium-connector

- name: "install elasticsearch instance"
  import_role:
    name: elasticsearch
