---

- name: "Install AMQ Streams operator"
  ansible.builtin.import_role:
    name: amq_streams_operator

- name: "Install ElasticSearch operator"
  ansible.builtin.import_role:
    name: elasticsearch_operator

- name: "Install OpenShift Gitops"
  ansible.builtin.import_role:
    name: openshift_gitops

- name: "Install Solution Pattern ArgoCD Application"
  ansible.builtin.import_role:
    name: gitops_solution_pattern_cdc
