---

- name: "install AMQ Streams operator"
  import_role:
    name: amq-streams-operator

- name: "install ElasticSearch operator"
  import_role:
    name: elasticsearch-operator

- name: "install Kafdrop"
  import_role:
    name: kafdrop

- name: "install retail-db database"
  import_role:
    name: retail-db

- name: "install cashback-db database"
  import_role:
    name: cashback-db

- name: "install Kafka Connect"
  import_role:
    name: kafka-connect

- name: "install debezium connector"
  import_role:
    name: debezium-connector

- name: "install elasticsearch instance"
  import_role:
    name: elasticsearch

- name: "install elasticsearch connector"
  import_role:
    name: elasticsearch-connector

- name: "install sales streams application"
  import_role:
    name: sales-streams-app

- name: "install cashback-connector"
  import_role:
    name: cashback-connector

- name: "install retail-simulation"
  import_role:
    name: retail-simulation
