---

- name: "uninstall cashback-connector"
  import_role:
    name: cashback-connector
    tasks_from: uninstall

- name: "uninstall slaes streams application"
  import_role:
    name: sales-streams-app
    tasks_from: uninstall

- name: "uninstall elasticsearch connector"
  import_role:
    name: elasticsearch-connector
    tasks_from: uninstall

- name: "uninstall elasticsearch instance"
  import_role:
    name: elasticsearch
    tasks_from: uninstall

- name: "uninstall Debezium connector"
  import_role:
    name: debezium-connector
    tasks_from: uninstall

- name: "uninstall Kafka Connect"
  import_role:
    name: kafka-connect
    tasks_from: uninstall

- name: "uninstall cashback-db database"
  import_role:
    name: cashback-db
    tasks_from: uninstall

- name: "uninstall retail-db database"
  import_role:
    name: retail-db
    tasks_from: uninstall
